name: Performance - Load Testing
on: [push]
jobs:
  load-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: node generate_load_test_report.js
        working-directory: ./e2e-testing
      - uses: actions/upload-artifact@v4
        with:
          name: Load_Testing_Report
          path: e2e-testing/Baseline_Load_Testing_Report.csv
